config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.4.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py -ID 10.23728/b2share.a1b9e55e087b45da8bc3982b0be9422e -R oai-pmh
          -B https://b2share.eudat.eu/api/oai2d --tool_endpoint http://localhost:9090/v1.0/rda/rda_all
        container: qc.fair_snazzy-malachite-quoll
timeout: 600
